= Gradle Plugin for downloading Asciidoctor PDF Themes

This Gradle plugin extends the https://github.com/asciidoctor/asciidoctor-gradle-plugin[asciidoctor-gradle-plugin].
It clones a Git repository, which contains a theme for Asciidoctor PDF.

== Example Theme

https://github.com/fwilhe/corporate-theme[Here] is an example repository for an Asciidoctor PDF theme.
Please note that the structure of the repository is mandatory for this plugin to work.
This means, that toplevel must be a directory `resources`.

For more information on Asciidoctor PDF themes, please consult https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc[Asciidoctor PDF Theming Guide].

== Usage

NOTE: This plugin requires the `org.asciidoctor.convert` and `org.asciidoctor:asciidoctorj-pdf` plugins.

Apply this plugin. Its plugin id is `com.github.fwilhe.asciidoctor-pdf-theme`.

To configure the theme, you need to specify a git repository and a name.
The name is what comes before the `-theme.yml` for your Asciidoctor PDF theme.

----
theme {
    url = 'git@someserver:lorem/ipsum-theme.git'
    name = 'ipsum'
}
----

You may optionally specify `themeVersion`, which must be a git tag.
If it is set, this tag will be checked out.
Otherwise the `master` branch will be checked out.

=== Example Document using this Plugin

https://github.com/fwilhe/asciidoctor-pdf-theme-gradle-plugin-example[Here] is an example gradle project using this plugin.

=== Development

For testing purposes, the plugin can be installed locally using

----
./gradlew publishToMavenLocal
----
